### ISSUE TITLE
Add recipe for using Granted with WSL and Windows Credential Manager

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#242]
The following setting works out of the box for Windows Credential Manager when running Granted in WSL, as reported by a community member.

```toml
[Keyring]
  Backend = "wincred"
```

We should document this so that other WSL users can easily discover it.
