### ISSUE TITLE
Support Safari as a default browser

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#247]
When using `assume` with a fresh MacOS install I receive the following:

```
chrisnorman@MacBook-Pro ~ % assume

ℹ️  Could not find default browser

? Select one of the browsers from the list  [Use arrows to move, type to filter]
> Chrome
  Brave
  Edge
  Firefox
  Chromium
  Stdout
  FirefoxStdout
```

Safari isn't included in this list - we should be able to detect it as a default browser or at least have it selectable in the list of browsers.

**Comment by chrnorm** [comment]
Even though I couldn't select Safari from the list, the settings that Granted created for me (TOML config below from `~/.granted/config`) do actually open Safari for logging in to AWS SSO.

```toml
DefaultBrowser = "FIREFOX"
CustomBrowserPath = "/Applications/Firefox.app/Contents/MacOS/firefox"
CustomSSOBrowserPath = ""
LastCheckForUpdates = 1
Ordering = ""
ExportCredentialSuffix = ""

[Keyring]
  Backend = "keychain"
```
