### ISSUE TITLE
`CustomBrowserPath` is required, even when using the new `AWSConsoleBrowserLaunchTemplate` setting

### ISSUE THREAD

**Issue by chrnorm** [common-fate/granted#753]
in #731 we added support for customising the AWS console browser launch template command:

```toml
[AWSConsoleBrowserLaunchTemplate]
  Command = "flatpak run org.mozilla.firefox --new-tab {{.URL}} --profile {{.Profile}}"
```

When this configuration is used though, `CustomBrowserPath` *has* to be set:

```toml
DefaultBrowser = "CUSTOM"
CustomBrowserPath = "foo"

[AWSConsoleBrowserLaunchTemplate]
  Command = "flatpak run org.mozilla.firefox --new-tab {{.URL}} --profile {{.Profile}}"
```

If it is not set, Granted shows the browser selection wizard: 

```
➜  ~ assume -c testing
[i] Thanks for using Granted!
[i] By default, Granted will open the AWS console with this browser: Chrome
[!] Granted works best with Firefox but also supports Chrome, Brave, and Edge (https://docs.commonfate.io/granted/introduction#supported-browsers). You can change this setting later by running 'granted browser set'
? Use Firefox as default Granted browser? No
[✔] Granted will default to using Chrome
? Use a different browser than your default browser for SSO login? No
[i] To change the web browser that Granted uses run: `granted browser -set`
```

The `UserHasDefaultBrowser` needs to be updated here to fix this.
